from pathlib import Path

DATA_ROOT = Path(r"E:\Projects\neuron_data")

# Material library manifest
LIBRARY_JSON = DATA_ROOT / "neuron_library.json"

# Synthetic dataset renders
DATASET_DIR = DATA_ROOT / "dataset"

# Camera transforms (generated by Houdini rig)
TRANSFORMS_JSON = DATA_ROOT / "transforms.json"

# Houdini node names
MATLIB_NODE = "neuron_materials"
HDA_NAME = "neuromat"

# Render passes subdirectory names
RENDER_PASSES = ["beauty", "albedo", "alpha", "normals"]
